# Generated by Django 6.0.3 on 2026-03-16 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255, unique=True)),
                ('PorcentajeGanancia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('IdProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IdProducto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('IdCategoria', models.ForeignKey(db_column='IdCategoria', on_delete=django.db.models.deletion.RESTRICT, to='catalogo.categoria')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
    ]
