# Generated by Django 6.0.3 on 2026-06-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_idproveedor_producto_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
