# Generated by Django 6.0.3 on 2026-03-16 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('IdEntradaInventario', models.AutoField(primary_key=True, serialize=False)),
                ('FechaEntrada', models.DateTimeField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IdProveedor', models.ForeignKey(db_column='IdProveedor', on_delete=django.db.models.deletion.RESTRICT, to='catalogo.proveedor')),
                ('IdUsuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EntradaInventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntradaInventario',
            fields=[
                ('IdDetalleEntrada', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('PrecioCompraUnitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IdProducto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.RESTRICT, to='catalogo.producto')),
                ('IdEntradaInventario', models.ForeignKey(db_column='IdEntradaInventario', on_delete=django.db.models.deletion.CASCADE, to='inventario.entradainventario')),
            ],
            options={
                'db_table': 'DetalleEntradaInventario',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('IdInventario', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido'), ('Perdido', 'Perdido'), ('Devuelto', 'Devuelto')], default='Disponible', max_length=20)),
                ('FechaMovimiento', models.DateTimeField()),
                ('IdDetalleEntrada', models.ForeignKey(db_column='IdDetalleEntrada', on_delete=django.db.models.deletion.RESTRICT, to='inventario.detalleentradainventario')),
            ],
            options={
                'db_table': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('IdPerdida', models.AutoField(primary_key=True, serialize=False)),
                ('TipoPerdida', models.CharField(choices=[('RechazoDevolucion', 'RechazoDevolucion'), ('Otra', 'Otra')], max_length=20)),
                ('Fecha', models.DateTimeField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IdUsuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Perdida',
            },
        ),
        migrations.CreateModel(
            name='DetallePerdida',
            fields=[
                ('IdDetallePerdida', models.AutoField(primary_key=True, serialize=False)),
                ('PrecioCompraUnitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IdInventario', models.ForeignKey(db_column='IdInventario', on_delete=django.db.models.deletion.RESTRICT, to='inventario.inventario')),
                ('IdPerdida', models.ForeignKey(db_column='IdPerdida', on_delete=django.db.models.deletion.CASCADE, to='inventario.perdida')),
            ],
            options={
                'db_table': 'DetallePerdida',
            },
        ),
        migrations.CreateModel(
            name='SolicitudDevolucion',
            fields=[
                ('IdSolicitudDevolucion', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('ParcialmenteAceptada', 'ParcialmenteAceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=25)),
                ('Observaciones', models.TextField(blank=True, null=True)),
                ('Fecha', models.DateTimeField()),
                ('IdEntradaInventario', models.ForeignKey(db_column='IdEntradaInventario', on_delete=django.db.models.deletion.RESTRICT, to='inventario.entradainventario')),
                ('IdUsuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SolicitudDevolucion',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudDevolucion',
            fields=[
                ('IdDetalleSolicitudDevolucion', models.AutoField(primary_key=True, serialize=False)),
                ('MotivoRechazo', models.TextField(blank=True, null=True)),
                ('PrecioCompraUnitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('EstadoItem', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=15)),
                ('IdInventario', models.ForeignKey(db_column='IdInventario', on_delete=django.db.models.deletion.RESTRICT, to='inventario.inventario')),
                ('IdSolicitudDevolucion', models.ForeignKey(db_column='IdSolicitudDevolucion', on_delete=django.db.models.deletion.CASCADE, to='inventario.solicituddevolucion')),
            ],
            options={
                'db_table': 'DetalleSolicitudDevolucion',
            },
        ),
    ]
