# Generated by Django 6.0.4 on 2026-04-19 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='Producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
            preserve_default=False,
        ),
    ]
