# Generated by Django 6.0.4 on 2026-04-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='Producto',
        ),
    ]
