# Generated by Django 6.0.3 on 2026-04-20 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_inventario_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleentradainventario',
            options={'ordering': ['-IdDetalleEntrada']},
        ),
        migrations.AlterModelOptions(
            name='detalleperdida',
            options={'ordering': ['-IdDetallePerdida']},
        ),
        migrations.AlterModelOptions(
            name='detallesolicituddevolucion',
            options={'ordering': ['-IdDetalleSolicitudDevolucion']},
        ),
        migrations.AlterModelOptions(
            name='entradainventario',
            options={'ordering': ['-IdEntradaInventario']},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-IdInventario']},
        ),
        migrations.AlterModelOptions(
            name='perdida',
            options={'ordering': ['-IdPerdida']},
        ),
        migrations.AlterModelOptions(
            name='solicituddevolucion',
            options={'ordering': ['-IdSolicitudDevolucion']},
        ),
        migrations.AlterField(
            model_name='inventario',
            name='FechaMovimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
