# Generated by Django 6.0.3 on 2026-04-23 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_detalleentradainventario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleentradainventario',
            name='Cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detalleentradainventario',
            name='PrecioCompraUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detalleperdida',
            name='PrecioCompraUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detallesolicituddevolucion',
            name='PrecioCompraUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='IdDetalleEntrada',
            field=models.ForeignKey(db_column='IdDetalleEntrada', on_delete=django.db.models.deletion.RESTRICT, related_name='inventarios', to='inventario.detalleentradainventario'),
        ),
        migrations.AlterField(
            model_name='perdida',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
