# Generated by Django 6.0.4 on 2026-04-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_detalleentradainventario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='IdDetalleEntrada',
            field=models.ForeignKey(db_column='IdDetalleEntrada', on_delete=django.db.models.deletion.RESTRICT, related_name='inventarios', to='inventario.detalleentradainventario'),
        ),
    ]
