# Generated by Django 6.0.3 on 2026-04-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_detalleentradainventario_cantidad_and_more'),
        ('inventario', '0005_alter_inventario_iddetalleentrada'),
    ]

    operations = [
    ]
