# Generated by Django 6.0.3 on 2026-03-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor')], default='vendedor', max_length=20),
        ),
    ]
