# Generated by Django 6.0.3 on 2026-03-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='EmailPendiente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='TokenVerificacion',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
