# Generated by Django 6.0.3 on 2026-05-21 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('IdLog', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=255)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('ERROR_ACCESO', 'Error de Acceso'), ('ANULAR', 'Anular'), ('PROCESAR', 'Procesar')], max_length=20)),
                ('modulo', models.CharField(choices=[('VENTAS', 'Ventas'), ('PRODUCTOS', 'Productos'), ('CATEGORIAS', 'Categorías'), ('PROVEEDORES', 'Proveedores'), ('INVENTARIO', 'Inventario'), ('PERDIDAS', 'Pérdidas'), ('DEVOLUCIONES', 'Devoluciones'), ('USUARIOS', 'Usuarios'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('descripcion', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido')], default='EXITOSO', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='IdUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'LogAuditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
