# Generated by Django 6.0.3 on 2026-03-16 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('IdVenta', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IdUsuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('IdDetalleVenta', models.AutoField(primary_key=True, serialize=False)),
                ('PrecioVentaUnitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IdInventario', models.ForeignKey(db_column='IdInventario', on_delete=django.db.models.deletion.RESTRICT, to='inventario.inventario')),
                ('IdVenta', models.ForeignKey(db_column='IdVenta', on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'db_table': 'DetalleVenta',
            },
        ),
    ]
