# Generated by Django 6.0.3 on 2026-04-23 04:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='Estado',
            field=models.CharField(choices=[('Completada', 'Completada'), ('Anulada', 'Anulada')], default='Completada', max_length=15),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='IdVenta',
            field=models.ForeignKey(db_column='IdVenta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='PrecioVentaUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
